# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: home_assistant.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14home_assistant.proto\x1a\x1bgoogle/protobuf/empty.proto\"H\n\nSensorData\x12\x12\n\nluminosity\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\t\x12\x11\n\tis_locked\x18\x03 \x01(\x08\"h\n\x0f\x41\x63tuatorCommand\x12\x0c\n\x04lock\x18\x01 \x01(\x08\x12\x1f\n\x17novo_nivel_luminosidade\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x05\x12\x11\n\tequipment\x18\x04 \x01(\t2\\\n\x1aTemperatureActuatorService\x12>\n\x12\x61lterarTemperatura\x12\x10.ActuatorCommand\x1a\x16.google.protobuf.Empty2\\\n\x19LuminosityActuatorService\x12?\n\x13\x61lterarLuminosidade\x12\x10.ActuatorCommand\x1a\x16.google.protobuf.Empty2S\n\x13LockActuatorService\x12<\n\x10\x61lterarFechadura\x12\x10.ActuatorCommand\x1a\x16.google.protobuf.Empty2\x8a\x01\n\x14HomeAssistantService\x12\x34\n\rGetSensorData\x12\x16.google.protobuf.Empty\x1a\x0b.SensorData\x12<\n\x10\x43ontrolActuators\x12\x10.ActuatorCommand\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'home_assistant_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENSORDATA']._serialized_start=53
  _globals['_SENSORDATA']._serialized_end=125
  _globals['_ACTUATORCOMMAND']._serialized_start=127
  _globals['_ACTUATORCOMMAND']._serialized_end=231
  _globals['_TEMPERATUREACTUATORSERVICE']._serialized_start=233
  _globals['_TEMPERATUREACTUATORSERVICE']._serialized_end=325
  _globals['_LUMINOSITYACTUATORSERVICE']._serialized_start=327
  _globals['_LUMINOSITYACTUATORSERVICE']._serialized_end=419
  _globals['_LOCKACTUATORSERVICE']._serialized_start=421
  _globals['_LOCKACTUATORSERVICE']._serialized_end=504
  _globals['_HOMEASSISTANTSERVICE']._serialized_start=507
  _globals['_HOMEASSISTANTSERVICE']._serialized_end=645
# @@protoc_insertion_point(module_scope)
